// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocols.Player {

  /// <summary>Holder for reflection information generated from PlayerData.proto</summary>
  public static partial class PlayerDataReflection {

    #region Descriptor
    /// <summary>File descriptor for PlayerData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBQbGF5ZXJEYXRhLnByb3RvEhBQcm90b2NvbHMuUGxheWVyIuoBCgpQbGF5",
            "ZXJEYXRhEhEKCXVzZXJfdXVpZBgBIAEoCRIUCgx1c2VyX2FjY291bnQYAiAB",
            "KAkSFQoNdXNlcl9wYXNzd29yZBgDIAEoCRIVCg1yZWdpc3Rlcl90aW1lGAQg",
            "ASgFEhcKD29ubGluZV9kdXJhdGlvbhgFIAEoBRIUCgxjaGFyZ2VfbW9uZXkY",
            "BiABKAUSGAoQZmluYWxfbG9naW5fdGltZRgHIAEoBRIXCg9maW5hbF9leGl0",
            "X3RpbWUYCCABKAUSEAoIZ3VpbGRfaWQYCSABKAUSEQoJaXNfb25saW5lGAog",
            "ASgIYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocols.Player.PlayerData), global::Protocols.Player.PlayerData.Parser, new[]{ "UserUuid", "UserAccount", "UserPassword", "RegisterTime", "OnlineDuration", "ChargeMoney", "FinalLoginTime", "FinalExitTime", "GuildId", "IsOnline" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 玩家数据结构
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerData : pb::IMessage<PlayerData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerData> _parser = new pb::MessageParser<PlayerData>(() => new PlayerData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocols.Player.PlayerDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerData(PlayerData other) : this() {
      userUuid_ = other.userUuid_;
      userAccount_ = other.userAccount_;
      userPassword_ = other.userPassword_;
      registerTime_ = other.registerTime_;
      onlineDuration_ = other.onlineDuration_;
      chargeMoney_ = other.chargeMoney_;
      finalLoginTime_ = other.finalLoginTime_;
      finalExitTime_ = other.finalExitTime_;
      guildId_ = other.guildId_;
      isOnline_ = other.isOnline_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerData Clone() {
      return new PlayerData(this);
    }

    /// <summary>Field number for the "user_uuid" field.</summary>
    public const int UserUuidFieldNumber = 1;
    private string userUuid_ = "";
    /// <summary>
    /// 玩家UUID (对应 SQL: user_uuid)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserUuid {
      get { return userUuid_; }
      set {
        userUuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_account" field.</summary>
    public const int UserAccountFieldNumber = 2;
    private string userAccount_ = "";
    /// <summary>
    /// 玩家账号 (对应 SQL: user_account)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserAccount {
      get { return userAccount_; }
      set {
        userAccount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_password" field.</summary>
    public const int UserPasswordFieldNumber = 3;
    private string userPassword_ = "";
    /// <summary>
    /// 玩家密码 (对应 SQL: user_password)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserPassword {
      get { return userPassword_; }
      set {
        userPassword_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "register_time" field.</summary>
    public const int RegisterTimeFieldNumber = 4;
    private int registerTime_;
    /// <summary>
    /// 注册时间 (对应 SQL: register_time)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RegisterTime {
      get { return registerTime_; }
      set {
        registerTime_ = value;
      }
    }

    /// <summary>Field number for the "online_duration" field.</summary>
    public const int OnlineDurationFieldNumber = 5;
    private int onlineDuration_;
    /// <summary>
    /// 在线时长 (对应 SQL: online_duration)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OnlineDuration {
      get { return onlineDuration_; }
      set {
        onlineDuration_ = value;
      }
    }

    /// <summary>Field number for the "charge_money" field.</summary>
    public const int ChargeMoneyFieldNumber = 6;
    private int chargeMoney_;
    /// <summary>
    /// 充值金额 (对应 SQL: charge_money)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChargeMoney {
      get { return chargeMoney_; }
      set {
        chargeMoney_ = value;
      }
    }

    /// <summary>Field number for the "final_login_time" field.</summary>
    public const int FinalLoginTimeFieldNumber = 7;
    private int finalLoginTime_;
    /// <summary>
    /// 最后登录时间 (对应 SQL: final_login_time)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FinalLoginTime {
      get { return finalLoginTime_; }
      set {
        finalLoginTime_ = value;
      }
    }

    /// <summary>Field number for the "final_exit_time" field.</summary>
    public const int FinalExitTimeFieldNumber = 8;
    private int finalExitTime_;
    /// <summary>
    /// 最后退出时间 (对应 SQL: final_exit_time)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FinalExitTime {
      get { return finalExitTime_; }
      set {
        finalExitTime_ = value;
      }
    }

    /// <summary>Field number for the "guild_id" field.</summary>
    public const int GuildIdFieldNumber = 9;
    private int guildId_;
    /// <summary>
    /// 公会ID (对应 SQL: guild_id)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GuildId {
      get { return guildId_; }
      set {
        guildId_ = value;
      }
    }

    /// <summary>Field number for the "is_online" field.</summary>
    public const int IsOnlineFieldNumber = 10;
    private bool isOnline_;
    /// <summary>
    /// 是否在线 (对应 SQL: is_online)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsOnline {
      get { return isOnline_; }
      set {
        isOnline_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserUuid != other.UserUuid) return false;
      if (UserAccount != other.UserAccount) return false;
      if (UserPassword != other.UserPassword) return false;
      if (RegisterTime != other.RegisterTime) return false;
      if (OnlineDuration != other.OnlineDuration) return false;
      if (ChargeMoney != other.ChargeMoney) return false;
      if (FinalLoginTime != other.FinalLoginTime) return false;
      if (FinalExitTime != other.FinalExitTime) return false;
      if (GuildId != other.GuildId) return false;
      if (IsOnline != other.IsOnline) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserUuid.Length != 0) hash ^= UserUuid.GetHashCode();
      if (UserAccount.Length != 0) hash ^= UserAccount.GetHashCode();
      if (UserPassword.Length != 0) hash ^= UserPassword.GetHashCode();
      if (RegisterTime != 0) hash ^= RegisterTime.GetHashCode();
      if (OnlineDuration != 0) hash ^= OnlineDuration.GetHashCode();
      if (ChargeMoney != 0) hash ^= ChargeMoney.GetHashCode();
      if (FinalLoginTime != 0) hash ^= FinalLoginTime.GetHashCode();
      if (FinalExitTime != 0) hash ^= FinalExitTime.GetHashCode();
      if (GuildId != 0) hash ^= GuildId.GetHashCode();
      if (IsOnline != false) hash ^= IsOnline.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserUuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserUuid);
      }
      if (UserAccount.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserAccount);
      }
      if (UserPassword.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UserPassword);
      }
      if (RegisterTime != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(RegisterTime);
      }
      if (OnlineDuration != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(OnlineDuration);
      }
      if (ChargeMoney != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ChargeMoney);
      }
      if (FinalLoginTime != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(FinalLoginTime);
      }
      if (FinalExitTime != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(FinalExitTime);
      }
      if (GuildId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(GuildId);
      }
      if (IsOnline != false) {
        output.WriteRawTag(80);
        output.WriteBool(IsOnline);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserUuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserUuid);
      }
      if (UserAccount.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserAccount);
      }
      if (UserPassword.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UserPassword);
      }
      if (RegisterTime != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(RegisterTime);
      }
      if (OnlineDuration != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(OnlineDuration);
      }
      if (ChargeMoney != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ChargeMoney);
      }
      if (FinalLoginTime != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(FinalLoginTime);
      }
      if (FinalExitTime != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(FinalExitTime);
      }
      if (GuildId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(GuildId);
      }
      if (IsOnline != false) {
        output.WriteRawTag(80);
        output.WriteBool(IsOnline);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserUuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserUuid);
      }
      if (UserAccount.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserAccount);
      }
      if (UserPassword.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserPassword);
      }
      if (RegisterTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RegisterTime);
      }
      if (OnlineDuration != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OnlineDuration);
      }
      if (ChargeMoney != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChargeMoney);
      }
      if (FinalLoginTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FinalLoginTime);
      }
      if (FinalExitTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FinalExitTime);
      }
      if (GuildId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GuildId);
      }
      if (IsOnline != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerData other) {
      if (other == null) {
        return;
      }
      if (other.UserUuid.Length != 0) {
        UserUuid = other.UserUuid;
      }
      if (other.UserAccount.Length != 0) {
        UserAccount = other.UserAccount;
      }
      if (other.UserPassword.Length != 0) {
        UserPassword = other.UserPassword;
      }
      if (other.RegisterTime != 0) {
        RegisterTime = other.RegisterTime;
      }
      if (other.OnlineDuration != 0) {
        OnlineDuration = other.OnlineDuration;
      }
      if (other.ChargeMoney != 0) {
        ChargeMoney = other.ChargeMoney;
      }
      if (other.FinalLoginTime != 0) {
        FinalLoginTime = other.FinalLoginTime;
      }
      if (other.FinalExitTime != 0) {
        FinalExitTime = other.FinalExitTime;
      }
      if (other.GuildId != 0) {
        GuildId = other.GuildId;
      }
      if (other.IsOnline != false) {
        IsOnline = other.IsOnline;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserUuid = input.ReadString();
            break;
          }
          case 18: {
            UserAccount = input.ReadString();
            break;
          }
          case 26: {
            UserPassword = input.ReadString();
            break;
          }
          case 32: {
            RegisterTime = input.ReadInt32();
            break;
          }
          case 40: {
            OnlineDuration = input.ReadInt32();
            break;
          }
          case 48: {
            ChargeMoney = input.ReadInt32();
            break;
          }
          case 56: {
            FinalLoginTime = input.ReadInt32();
            break;
          }
          case 64: {
            FinalExitTime = input.ReadInt32();
            break;
          }
          case 72: {
            GuildId = input.ReadInt32();
            break;
          }
          case 80: {
            IsOnline = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserUuid = input.ReadString();
            break;
          }
          case 18: {
            UserAccount = input.ReadString();
            break;
          }
          case 26: {
            UserPassword = input.ReadString();
            break;
          }
          case 32: {
            RegisterTime = input.ReadInt32();
            break;
          }
          case 40: {
            OnlineDuration = input.ReadInt32();
            break;
          }
          case 48: {
            ChargeMoney = input.ReadInt32();
            break;
          }
          case 56: {
            FinalLoginTime = input.ReadInt32();
            break;
          }
          case 64: {
            FinalExitTime = input.ReadInt32();
            break;
          }
          case 72: {
            GuildId = input.ReadInt32();
            break;
          }
          case 80: {
            IsOnline = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
